---
title: "Untitled"
author: "Jian(Frank)"
date: "27/01/2022"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
source("scripts/pkgs.R")

```


```{r}
data <- fread("Data/lmtestrs.csv")
data %>% 
  melt.data.table(variable.factor = FALSE) %>% 
  ggplot(aes(value, fill = variable)) +
  geom_histogram( position = position_dodge(),binwidth = 300, bins = 30) +
  min_theme() +
  theme(legend.position = c(.9,.85),
        legend.background = element_rect(colour = "black"),
        legend.box.background = element_rect(colour = "white"),
        legend.title = element_blank(),
        title = element_text(size = 18, face = "bold"),
         axis.text = element_text(size = 13),
         axis.title = element_text(size = 16, vjust =  "rt"),
         plot.margin = margin(30, 30, 30, 30), 
         panel.spacing =  grid::unit(2, "lines"))+
  labs(x = "Item Outlet Sales", 
       y = "Distribution",
       title = "True Sales vs Predicted Sales Distribution Comparision",
       subtitle = "Linear Regression Model")+
      scale_fill_manual(name = '', values = corporate_colors[c(2, 4)], labels = c("True Sales", "Predict Sales") )


ggsave("Reports/true_pred.png", width = 9, height = 6, dpi = 300)


```


```{r}
baselines <- fread("Data/baselines.csv")
rank =baselines[, mean(r2), by = .(names)
          ][order(V1, decreasing = T)][, rank := 1:.N]

baselines$names <- factor(baselines$names, levels = rank$names)
baselines %>% 
  ggplot(aes(names, r2)) +
  geom_boxplot() +
  min_theme() +
  theme(title = element_text(size = 18, face = "bold"),
        axis.text = element_text(size = 13), 
        plot.caption = element_text(size = 12),
        axis.title = element_text(size = 16, vjust =  "rt"),
        plot.margin = margin(30, 30, 30, 30), 
        panel.spacing =  grid::unit(2, "lines"))+
  labs(x = "Models", 
       y = "Coefficient of determination",
       title = "Six Models Performance Evaluation",
       caption = "Boxplot resulted from 10 fold cross validation ")



ggsave("Reports/modelseletion.png", width = 9, height = 6, dpi = 300)

  
```
## visual glm features

```{r}
glm <- fread("Data/glm.csv")
glm <- glm %>% 
  melt.data.table(variable.factor = FALSE)
glm[value > 0.01][order(value, decreasing = T)][1:5] %>% 
  ggplot(aes(fct_reorder(variable, value),value)) +
  geom_col(fill = corporate_colors) +
  coord_flip() +
  min_theme()+
  labs(x = "Features", 
       y = "Coefficient",
       title = "Top Five Predictors",
       subtitle = "Generalised Linear Model")+
      scale_fill_manual(name = '', values = corporate_colors[c(2, 4)], labels = c("True Sales", "Predict Sales") )


ggsave("Reports/glmfeatureranks.png", width = 9, height = 6, dpi = 300)
```

## visual rf grid search 

```{r}
top10_rf_para <- fread("Data/rf_gridsearch.csv")
cols <- colnames(top10_rf_para)
top10_rf_para[, para_combi := paste(bootstrap,max_depth,max_features,n_estimators, sep = "\n")]
top10_rf_para %>% 
  ggplot(aes(rank_test_score, mean_test_score)) +
  geom_line()
  
```
```{r}
topfeatures <- fread("Data/rf_featureimpt.csv")

topfeatures[value > 0.001] %>% 
  ggplot(aes(forcats::fct_reorder(V1, value),value)) +
  geom_col(fill = corporate_colors[c(5, 5:1)]) +
  coord_flip() +
  min_theme()+
  labs(x = "Features", 
       y = "Importance",
       title = "Top Five Predictors",
       subtitle = "Random Forest")


ggsave("Reports/rffeatureranks.png", width = 9, height = 6, dpi = 300)

```


```{r}
data <- fread("Data/BigMart.csv")
data[, lapply(.SD, function(x) sum(is.na(x)))]
colnames(data)

```
## Leave out the item weight for now 

```{r}
sub <- data[!is.na(Item_Weight)][, Item_Identifier := NULL]
sub[, V1:=NULL]

# creat dummy variables 
# ?model.matrix
model_m <- model.matrix(Item_Outlet_Sales~., data = sub) %>% 
  as.data.frame()
model_m_df <- cbind(model_m, sub[,.(Item_Outlet_Sales)])

```


# Split data
```{r}

```

```{r}

set.seed(42)
trainidx <- createDataPartition(model_m_df$Item_MRP, p = .8,
                                list = FALSE)

str(trainidx)
train <- model_m_df[trainidx,]
test <- model_m_df[-trainidx,]
colnames(train)
colnames(test)
```
# Parameter tuning 

```{r}
fitControl <- trainControl(## 10-fold CV
                           method = "repeatedcv",
                           number = 10,
                           ## repeated ten times
                           repeats = 10)
```

```{r, warning=FALSE}
set.seed(42)
lmFit1 <- train(Item_Outlet_Sales ~ ., data = train, 
                method = "lm", 
                trControl = fitControl, 
                preProcess = "center")
pred <- predict(lmFit1, test)
lmFit1
postResample(pred = pred, obs = test$Item_Outlet_Sales)

glmFit1 <- train(Item_Outlet_Sales ~ ., data = train, 
                method = "glm", 
                trControl = fitControl, 
                preProcess = "center")
pred_glm <- predict(glmFit1, test)
saveRDS(glmFit1, "Data/glmfit1")
postResample(pred = pred_glm, obs = test$Item_Outlet_Sales)


l1Fit1 <- train(Item_Outlet_Sales ~ ., data = train, 
                method = "blassoAveraged", 
                trControl = fitControl, 
                preProcess = "center")
# pred_l1 <- predict(l1Fit1, test)
# saveRDS(l1Fit1, "Data/l2fit1")
postResample(pred = pred_l1, obs = test$Item_Outlet_Sales)

## rf is super slow 
# rfFit1 <- train(Item_Outlet_Sales ~ ., data = train, 
#                 method = "rf", 
#                 trControl = fitControl, 
#                 preProcess = "center")
# pred_rf <- predict(rfFit1, test)

# postResample(pred = pred_rf, obs = test$Item_Outlet_Sales)

```

```{r}
length(pred)
nrow(test)
pred <- data.frame(pred = pred, obs = test$Item_Outlet_Sales)
ggplot(pred, aes(obs, pred)) +
  geom_point() 
```

```{r}
set.seed(42)
# gbmFit1  <- train(Item_Outlet_Sales ~ ., data = train, 
#                 method = "gbm", 
#                 trControl = fitControl, 
#                 preProcess = "center")
```

#  
```{r}
colnames(data)
lm1 <- lm(log(Item_Outlet_Sales) ~ Item_MRP, data = data)
summary(lm1)

```

